[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-attributes = "1.1.2"
async-std = "1.12.0"
serde = "1.0.196"
tide = "0.16.0"
